title: Dayi Fan
# nickname: Davis
position: Ph.D. Student
affiliation: The Ohio State University
email: fan.1090 (at) osu (dot) edu
keywords: minimal academic
# google_scholar: https://scholar.google.com/
github_link: https://github.com/Davis-Fan
# linkedin: https://www.linkedin.com/in/tianyu-xiong-b485bb154/
avatar: ./assets/img/Dayi_Profile.JPG
# google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
